# Generated by Django 3.2.5 on 2021-08-17 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Abcdin'), ('2', 'Hites'), ('3', 'La Polar')], max_length=45)),
                ('rut', models.CharField(max_length=45)),
                ('warehouse_origin', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beetrack_state', models.CharField(choices=[('Entregado', 'Entregado'), ('Pendiente', 'Pendiente'), ('No Entregado', 'No Entregado'), ('Entrega Parcial', 'No Retirado'), ('Retirado', 'Retirado')], default='Inicial', max_length=70)),
                ('beetrack_substate', models.CharField(choices=[('Domicilio sin moradores', 'Domicilio sin moradores'), ('Domicilio no corresponde', 'Domicilio no corresponde'), ('Cliente Anula Compra', 'Cliente Anula Compra'), ('Producto No Corresponde', 'Producto No Corresponde'), ('Producto Danado', 'Producto Danado'), ('Camion Siniestrado', 'Camion Siniestrado'), ('Camion en Panne', 'Camion en Panne'), ('Despacho Duplicado', 'Despacho Duplicado'), ('Retiro no realizado', 'Retiro no realizado'), ('Retiro y Cambio no realizado', 'Retiro y Cambio no realizado'), ('Fuera de Horario', 'Fuera de Horario'), ('Producto Incompleto', 'Producto Incompleto'), ('Reagendamiento por Cliente', 'Reagendamiento por Cliente'), ('Acceso Inaccsesible', 'Acceso Inaccsesible'), ('Devolucion a CD', 'Devolucion a CD'), ('Devolucion', 'Devolucion')], default='Inicial', max_length=70)),
                ('beetrack_comment', models.TextField()),
                ('date_return', models.DateField(blank=True, default='2021-01-01', null=True)),
                ('dev_state', models.CharField(choices=[('Domicilio sin moradores', 'Domicilio sin moradores'), ('Domicilio no corresponde', 'Domicilio no corresponde'), ('Cliente Anula Compra', 'Cliente Anula Compra'), ('Producto No Corresponde', 'Producto No Corresponde'), ('Producto Danado', 'Producto Danado'), ('Camion Siniestrado', 'Camion Siniestrado'), ('Camion en Panne', 'Camion en Panne'), ('Despacho Duplicado', 'Despacho Duplicado'), ('Retiro no realizado', 'Retiro no realizado'), ('Retiro y Cambio no realizado', 'Retiro y Cambio no realizado'), ('Fuera de Horario', 'Fuera de Horario'), ('Producto Incompleto', 'Producto Incompleto'), ('Reagendamiento por Cliente', 'Reagendamiento por Cliente'), ('Acceso Inaccsesible', 'Acceso Inaccsesible'), ('Devolucion a CD', 'Devolucion a CD'), ('Devolucion', 'Devolucion')], default='Inicial', max_length=70)),
                ('dev_comment', models.TextField()),
                ('dev_reason', models.CharField(choices=[('Anula Compra', 'Anula Compra'), ('Rechazo Px no Corresponde', 'Rechazo Px no Corresponde'), ('Rechazo Px danado', 'Rechazo Px danado'), ('Decision Comercial', 'Decision Comercial'), ('Desiste Compra', 'Desiste Compra')], default='Inicial', max_length=70)),
                ('dev_condition', models.CharField(choices=[('Embalaje Completo Px Noble', 'Embalaje Completo Px Noble'), ('Emalaje Incompleto Px Noble', 'Emalaje Incompleto Px Noble'), ('Sin Embalaje Px Noble', 'Sin Embalaje Px Noble'), ('Estado Px a todo evento', 'Estado Px a todo evento')], default='Inicial', max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=70)),
                ('rol', models.CharField(default='USER', max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('birdth_date', models.DateField()),
                ('entry_date', models.DateField()),
                ('position', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personals', to='app_dev.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_origin', models.CharField(max_length=45)),
                ('date_issue', models.DateField(blank=True, null=True)),
                ('origin_order', models.CharField(max_length=45)),
                ('order_number', models.CharField(max_length=45)),
                ('ticket_number', models.CharField(max_length=45)),
                ('type_order', models.CharField(max_length=45)),
                ('product', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('number_packager', models.IntegerField()),
                ('sku', models.CharField(max_length=45)),
                ('record', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_company', to='app_dev.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_user', to='app_dev.user')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states_delivery', to='app_dev.statedelivery')),
                ('warehouse_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_warehouse', to='app_dev.warehouse')),
            ],
        ),
    ]
