from django.urls import path
from . import views
urlpatterns = [
    path('', views.index),
    path('administrador/registro', views.registro),
    path('administrador/usuario', views.user),
    path('administrador/bodega/crear', views.newWarehouse),
    path('administrador/bodega', views.warehouse),
    path('administrador/cliente/crear', views.newCompany),
    path('administrador/cliente', views.company),
    path('administrador/personal/crear', views.newPersonal),
    path('administrador/personal', views.personal),
    path('inversa/data/registro', views.newIorder),
    path('inversa/data', views.dataInversa),
    path('inversa/guia/<int:id>', views.guideOrder),
    path('inversa/guia/<int:id>/edit', views.guideOrderEdit),
    path('logearse',views.logearse),
    path('panel',views.panel),
    path('logout',views.logout),
    path('administrador',views.administrador),
    path('reporte',views.reporte),
    path('inversa',views.inversa),
    path('inversa/cargo',views.infCargo),
    path('bodega/osorno',views.warehouseOsorno),
    path('bodega/osorno/data/devolucion',views.warehouseOsornoDev),
    path('bodega/osorno/data/devolucion/guia/<int:id>',views.guideOrderOsorno),
    path('bodega/puerto-montt',views.warehousePuerto),
    path('bodega/puerto-montt/data/devolucion',views.warehousePuertoDev),
    path('bodega/puerto-montt/data/devolucion/guia/<int:id>',views.guideOrderPuerto),
    path('bodega/temuco',views.warehouseTemuco),
    path('bodega/temuco/cargos',views.cargoTemuco),
    path('bodega/temuco/cargos/guia/<int:id>',views.cargoTemucoGuia),
    path('bodega/temuco/data/devolucion',views.warehouseTemucoDev),
    path('bodega/temuco/data/devolucion/guia/<int:id>',views.guideOrderTemuco),
    path('bodega/temuco/data-general',views.warehouseTemucoDataGeneral),
    path('bodega/temuco/data-general/guia/<int:id>',views.guideOrderTemucoGeneral)
]
